# Generated by Django 5.2.6 on 2025-09-23 10:02

import django.core.validators
import django.db.models.deletion
import django_tenants.postgresql_backend.base
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('business_name', models.CharField(max_length=255, unique=True)),
                ('business_type', models.CharField(choices=[('isp', 'Internet Service Provider'), ('hotel', 'Hotel'), ('restaurant', 'Restaurant'), ('campus', 'Campus/University'), ('residential', 'Residential Complex'), ('other', 'Other')], default='isp', max_length=20)),
                ('business_email', models.EmailField(max_length=254, unique=True)),
                ('business_phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('website', models.URLField(blank=True, null=True)),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=15)),
                ('license_status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('suspended', 'Suspended'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('license_start_date', models.DateField(blank=True, null=True)),
                ('license_end_date', models.DateField(blank=True, null=True)),
                ('license_duration_days', models.PositiveIntegerField(default=365, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_users', models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_active_sessions', models.PositiveIntegerField(default=200, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_trial', models.BooleanField(default=True)),
                ('trial_start_date', models.DateField(blank=True, null=True)),
                ('trial_end_date', models.DateField(blank=True, null=True)),
                ('trial_duration_days', models.PositiveIntegerField(default=14, validators=[django.core.validators.MinValueValidator(1)])),
                ('platform_fee_percentage', models.DecimalField(decimal_places=2, default=15.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'ordering': ['business_name'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': 'Domains',
            },
        ),
    ]
